### ISSUE TITLE
关于环境问题

### ISSUE THREAD

**Issue by Stitchsong** [proteus1991/PSCC-Net#10]
作者你好，不知道是不是你更新了新的代码以后把之前的环境配置相关信息给覆盖掉了，目前这个代码没有环境配置的具体信息，请问你可以提供一份这个代码的相关环境配置吗？
感谢！

**Comment by proteus1991** [comment]
你好，这个算法并没有用到特别的依赖，我想正常的pytorch+cuda环境都能运行这个程序。如果你遇到了具体问题，欢迎咨询。
