### ISSUE TITLE
Regarding the image size of evaluation

### ISSUE THREAD

**Issue by dkarageo** [proteus1991/PSCC-Net#11]
Hello and thank you for your very interesting work,

While I was experimenting with the provided pre-trained models I found out that the results were worse when the images were utilized on their original size compared to when they were limited to 256x256 (by retaining aspect ratio). An example dataset to reproduce the issue is Columbia. 

So, I would like to ask you what is the input size that leads to the best results? What was the one utilized during the evaluation reported in the paper?

**Comment by ORainn** [comment]
Hello, I have the same question. Also, could you please share the code you used for testing? My code encountered an issue with Out Of Memory on high-resolution images.

**Comment by proteus1991** [comment]
> Hello and thank you for your very interesting work,
> 
> While I was experimenting with the provided pre-trained models I found out that the results were worse when the images were utilized on their original size compared to when they were limited to 256x256 (by retaining aspect ratio). An example dataset to reproduce the issue is Columbia.
> 
> So, I would like to ask you what is the input size that leads to the best results? What was the one utilized during the evaluation reported in the paper?

Since the network was trained with the image size of 256x256, it may achieve the best performance on the similar scale, but I used the original image size for evaluation.
