### ISSUE TITLE
splice/mask

### ISSUE THREAD

**Issue by xiong76** [proteus1991/PSCC-Net#13]
![1688371498375](https://github.com/proteus1991/PSCC-Net/assets/55030859/39730347-30fe-4e99-9c43-342f569754d7)
The datasets(splice)  you provided doesn't exist the floder of mask,Can you provide it ?Thanks!!

**Comment by proteus1991** [comment]
Hi, the dataset is complete and you can find the mask folder in the provided dataset link.
