### ISSUE TITLE
About the Training Datasets

### ISSUE THREAD

**Issue by FathUMinUllah3797** [proteus1991/PSCC-Net#15]
Hi,

I wanted to download the datasets that you provided in Baidu Cloud, however, I don't have an account with it and registration requires a cell number based in China. Could you provide me other link having the same contents?

Thank you.

**Comment by proteus1991** [comment]
Hi, I really wish to provide more options for dataset download. However, I cannot find any other places except for Baidu Cloud that could save the dataset more than 20GB online for free. If you know the places, please let me know.

**Comment by FathUMinUllah3797** [comment]
Next, why do you chose train_num = 100000? and pscc_args.val_num = 200
