### ISSUE TITLE
About training results

### ISSUE THREAD

**Issue by cocotorrow** [proteus1991/PSCC-Net#18]
**Hello, why is the result like this when I run the train file?**

=> loading HRNet pretrained model models/hrnet_w18_small_v2.pth
HRNet weight-loading succeeds: ./checkpoint/HRNet_checkpoint/HRNet.pth
NLCDetection weight-loading succeeds: ./checkpoint/NLCDetection_checkpoint/NLCDetection.pth
DetectionHead weight-loading succeeds: ./checkpoint/DetectionHead_checkpoint/DetectionHead.pth
length of traindata: 500
previous_score 0.9871
authentic_ratio: 0.25 fake_ratio: 0.75
resuming FENet by loading epoch 30
resuming SegNet by loading epoch 30
resuming ClsNet by loading epoch 30

Process finished with exit code 0

**Comment by FathUMinUllah3797** [comment]
@YchenJsy . It means, you have trained the model for 30 epochs and in next training, the model see previously trained checkpoints and give the prediction based on them. If you move them out, it will start training again. 

This is what I experienced too.

**Comment by proteus1991** [comment]
@FathUMinUllah3797 Thanks for helping me answer the question. Yes, your understanding is correct. 

@YchenJsy If you have any further question, please reopen this issue.

**Comment by YchenJsy** [comment]
> @YchenJsy . It means, you have trained the model for 30 epochs and in next training, the model see previously trained checkpoints and give the prediction based on them. If you move them out, it will start training again.
> 
> This is what I experienced too.

**Comment by YchenJsy** [comment]
> ex



> @YchenJsy . It means, you have trained the model for 30 epochs and in next training, the model see previously trained checkpoints and give the prediction based on them. If you move them out, it will start training again.
> 
> This is what I experienced too.
thanks for your explanation

**Comment by cocotorrow** [comment]
@FathUMinUllah3797  thanks for your explanation  !
