### ISSUE TITLE
search for help

### ISSUE THREAD

**Issue by chenxinshuang** [proteus1991/PSCC-Net#4]
Thank you for opening the source code of your work. This work is excellent. I downloaded the code and parameter weights you provided. Because I didn't see your evaluation  code, I used my own evaluation indicator code, and the test results are somewhat different from your results. The following is my evaluation index method and test results. Can you share the code of your evaluation or point out my mistakes
![tempsnip](https://user-images.githubusercontent.com/54966102/197441126-5ff8b5df-bd90-4a14-9346-a352878c8eb2.png)
![111](https://user-images.githubusercontent.com/54966102/197441174-f84325a1-97f1-44b0-b1f2-69f5a9d69b16.JPG)
![222](https://user-images.githubusercontent.com/54966102/197441180-97b617ff-8c5c-400e-8ae3-8961331c3224.JPG)

**Comment by zyqss** [comment]
hellod，Are you using the weights provided in the checkpoint‘s file? Why did I only reach 70% on casiav1? 
And I try to retain the net using my datasets only with splicing images，it gets a terrible process, I wonder whether you can train with a reseanable process.

**Comment by chenxinshuang** [comment]
I retrain the model and then test on these datasets ,but the result is worth than tested with the pretrained weight the author give.

**Comment by zyqss** [comment]
> I retrain the model and then test on these datasets ,but the result is worth than tested with the pretrained weight the author give.

Thanks. I have trouble in training, can I contact you in QQ?

**Comment by chenxinshuang** [comment]
ok,my qq is 1509420994

**Comment by asdjia** [comment]
Hi, may I ask how did you download the NIST16 dataset with 564 images. I downloaded it, but the number of images is not the same(like about 1,000 images in total).

**Comment by proteus1991** [comment]
> Hi, may I ask how did you download the NIST16 dataset with 564 images. I downloaded it, but the number of images is not the same(like about 1,000 images in total).

We have provided the name list for NIST16 dataset in ```dataset/test/NIST16```. Hope this could help you.

**Comment by proteus1991** [comment]
I used the ```sklearn``` package for measurement. More details can be found in  #2  . Also, it is worth noting that the forged region in some images might be greater than 50% of the whole image. In those cases, the PSCC-Net might treat the smaller region as forged (e.g., the spliced region). Since localizing the greater or smaller region as the forged region is both reasonable in practical applications, we use 1-AUC as the final score if the AUC score is lower than 50%.

**Comment by xupinggl** [comment]
test.py中报错，找不到splice_metrics_new，能否麻烦作者公开下，非常感谢

**Comment by ORainn** [comment]
Hello, I have the same question. Also, could you please share the code you used for testing? My code encountered an Out of Memory issue on high-resolution images, such as IMD20 and NIST16.

**Comment by Liminglud** [comment]
> 我用这个`sklearn`包来测量。[更多细节可以在#2](https://github.com/proteus1991/PSCC-Net/issues/2)中找到 。另外，值得注意的是，某些图像中的伪造区域可能大于整个图像的 50%。在这些情况下，PSCC-Net 可能会将较小的区域视为伪造的（例如，拼接区域）。由于在实际应用中将较大或较小的区域定位为伪造区域都是合理的，因此如果 AUC 分数低于 50%，我们使用 1-AUC 作为最终分数。

Hello,  could you please tell me if you have done a similar calculation for f1, I retrained the model and finetured on CASIAV2 dataset. Then I calculated AUC score which is  consistent with what you said(87.08), but f1 score is only 44.04

**Comment by xupinggl** [comment]
您好，您的邮件我已收到，我会尽快回复的，谢谢！

**Comment by cocotorrow** [comment]
> Hello, I have the same question. Also, could you please share the code you used for testing? My code encountered an Out of Memory issue on high-resolution images, such as IMD20 and NIST16.

你解决这个问题了吗,我也遇见了同样的问题

**Comment by hezw2016** [comment]
> > 我用这个`sklearn`包来测量。[更多细节可以在#2](https://github.com/proteus1991/PSCC-Net/issues/2)中找到 。另外，值得注意的是，某些图像中的伪造区域可能大于整个图像的 50%。在这些情况下，PSCC-Net 可能会将较小的区域视为伪造的（例如，拼接区域）。由于在实际应用中将较大或较小的区域定位为伪造区域都是合理的，因此如果 AUC 分数低于 50%，我们使用 1-AUC 作为最终分数。
> 
> Hello, could you please tell me if you have done a similar calculation for f1, I retrained the model and finetured on CASIAV2 dataset. Then I calculated AUC score which is consistent with what you said(87.08), but f1 score is only 44.04

Hey, I got similar pixel-level F1 score on CASIA V1 with the .pth weights provided by the authors, which is about 46%.

**Comment by xupinggl** [comment]
您好，您的邮件我已收到，我会尽快回复的，谢谢！
