### ISSUE TITLE
why does PCSS-net have poor results on the CoMoFoD_small_v2 dataset?

### ISSUE THREAD

**Issue by SDWDD** [proteus1991/PSCC-Net#6]
![Snipaste_2022-11-21_10-52-27](https://user-images.githubusercontent.com/43052869/202960506-dc6b4c58-47b8-466c-81c5-b79e2065bc12.png)

**Comment by SDWDD** [comment]
![Snipaste_2022-11-21_10-52-27](https://user-images.githubusercontent.com/43052869/202953160-5da17886-ae1c-4a7f-bbce-f033b4b29618.png)

**Comment by SDWDD** [comment]
What do I need to do to improve model performance? Please tell me that I am only a beginner

**Comment by proteus1991** [comment]
Hi, thanks for your interest in our work. The generalization ability is always the key challenge for image manipulation detection and localization task. Owing to the imperfect of our training data, the PSCC-Net might not study the manipulation traces in CoMoFoD_small_v2 dataset, thus resulting in inferior performance. One solution is to fine-tune the PSCC-Net in the training split of CoMoFoD_small_v2 dataset. I believe this could greatly improve the performance in testing.
