### ISSUE TITLE
errors in the test.py

### ISSUE THREAD

**Issue by AlfredQin** [proteus1991/PSCC-Net#9]
Hi, @proteus1991 , I find there are some undefined variables in the test.py and could you please check it? thank you !

**Comment by xupinggl** [comment]
I meet the same problem。utils.py can not find splice_metrics_new.  @proteus1991 Could you  releases the code, thank you very much.

**Comment by proteus1991** [comment]
Hi guys, in my last push for the release of data generation codes, I found that I wrongly overwrited the ```test.py``` and ```./utils/utils.py```. Now, the issue has been solved. Sorry for any inconvenience.

**Comment by xupinggl** [comment]
您好，您的邮件我已收到，我会尽快回复的，谢谢！
